### ISSUE TITLE
Fix the combat section going to the bottom of the screen

### ISSUE THREAD

**Issue by Savvakos7** [Coffee-Client/Coffee#53]
Everytime I open Minecraft the combat section is not where I left it and I have to change screen resolution and put it in the right place again

**Comment by 0x3C50** [comment]
thats because the gui currently doesn't save the position, and the max height of each tab is just enough to put the next one out of view. It's wrapping around to the next row if there's no more space, thats why it doesn't show up. I'll make it save the positions at some point, but I'm on holiday rn so I can't do it just yet

**Comment by Savvakos7** [comment]
> thats because the gui currently doesn't save the position, and the max height of each tab is just enough to put the next one out of view. It's wrapping around to the next row if there's no more space, thats why it doesn't show up. I'll make it save the positions at some point, but I'm on holiday rn so I can't do it just yet

Ok I'll wait,have good holidays
